<a href="https://colab.research.google.com/github/ritesh97b/NumPy/blob/master/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
ratings1=pd.read_csv("imdb.csv", error_bad_lines=False)
ratings1.head()

b'Skipping line 66: expected 44 fields, saw 46\nSkipping line 111: expected 44 fields, saw 45\nSkipping line 198: expected 44 fields, saw 45\nSkipping line 222: expected 44 fields, saw 46\nSkipping line 278: expected 44 fields, saw 45\nSkipping line 396: expected 44 fields, saw 45\nSkipping line 403: expected 44 fields, saw 45\nSkipping line 421: expected 44 fields, saw 45\nSkipping line 437: expected 44 fields, saw 45\nSkipping line 462: expected 44 fields, saw 46\nSkipping line 491: expected 44 fields, saw 45\nSkipping line 515: expected 44 fields, saw 45\nSkipping line 529: expected 44 fields, saw 45\nSkipping line 530: expected 44 fields, saw 45\nSkipping line 558: expected 44 fields, saw 45\nSkipping line 623: expected 44 fields, saw 45\nSkipping line 646: expected 44 fields, saw 45\nSkipping line 663: expected 44 fields, saw 46\nSkipping line 713: expected 44 fields, saw 45\nSkipping line 730: expected 44 fields, saw 47\nSkipping line 791: expected 44 fields, saw 45\nSkipping line 813: expected 44 fields, saw 45\nSkipping line 837: expected 44 fields, saw 45\nSkipping line 861: expected 44 fields, saw 45\nSkipping line 874: expected 44 fields, saw 45\nSkipping line 899: expected 44 fields, saw 45\nSkipping line 917: expected 44 fields, saw 45\nSkipping line 944: expected 44 fields, saw 46\nSkipping line 994: expected 44 fields, saw 45\nSkipping line 1027: expected 44 fields, saw 45\nSkipping line 1046: expected 44 fields, saw 45\nSkipping line 1097: expected 44 fields, saw 45\nSkipping line 1106: expected 44 fields, saw 45\nSkipping line 1170: expected 44 fields, saw 45\nSkipping line 1194: expected 44 fields, saw 45\nSkipping line 1195: expected 44 fields, saw 45\nSkipping line 1218: expected 44 fields, saw 45\nSkipping line 1220: expected 44 fields, saw 45\nSkipping line 1270: expected 44 fields, saw 45\nSkipping line 1338: expected 44 fields, saw 47\nSkipping line 1355: expected 44 fields, saw 45\nSkipping line 1363: expected 44 fields, saw 45\nSkipping line 1395: expected 44 fields, saw 45\nSkipping line 1402: expected 44 fields, saw 46\nSkipping line 1418: expected 44 fields, saw 45\nSkipping line 1431: expected 44 fields, saw 45\nSkipping line 1617: expected 44 fields, saw 45\nSkipping line 1663: expected 44 fields, saw 45\nSkipping line 1742: expected 44 fields, saw 46\nSkipping line 1766: expected 44 fields, saw 45\nSkipping line 1799: expected 44 fields, saw 45\nSkipping line 1867: expected 44 fields, saw 45\nSkipping line 1899: expected 44 fields, saw 45\nSkipping line 1900: expected 44 fields, saw 45\nSkipping line 1901: expected 44 fields, saw 45\nSkipping line 1907: expected 44 fields, saw 45\nSkipping line 1913: expected 44 fields, saw 45\nSkipping line 1924: expected 44 fields, saw 45\nSkipping line 1939: expected 44 fields, saw 45\nSkipping line 1945: expected 44 fields, saw 45\nSkipping line 1982: expected 44 fields, saw 45\nSkipping line 2023: expected 44 fields, saw 45\nSkipping line 2028: expected 44 fields, saw 45\nSkipping line 2054: expected 44 fields, saw 45\nSkipping line 2076: expected 44 fields, saw 45\nSkipping line 2081: expected 44 fields, saw 45\nSkipping line 2092: expected 44 fields, saw 45\nSkipping line 2107: expected 44 fields, saw 45\nSkipping line 2160: expected 44 fields, saw 45\nSkipping line 2260: expected 44 fields, saw 45\nSkipping line 2261: expected 44 fields, saw 45\nSkipping line 2289: expected 44 fields, saw 46\nSkipping line 2290: expected 44 fields, saw 45\nSkipping line 2349: expected 44 fields, saw 45\nSkipping line 2395: expected 44 fields, saw 45\nSkipping line 2507: expected 44 fields, saw 45\nSkipping line 2584: expected 44 fields, saw 45\nSkipping line 2588: expected 44 fields, saw 46\nSkipping line 2595: expected 44 fields, saw 45\nSkipping line 2604: expected 44 fields, saw 45\nSkipping line 2622: expected 44 fields, saw 45\nSkipping line 2661: expected 44 fields, saw 45\nSkipping line 2714: expected 44 fields, saw 45\nSkipping line 2722: expected 44 fields, saw 45\nSkipping line 2776: expected 44 fields, saw 45\nSkipping line 2806: expected 44 fields, saw 45\nSkipping line 2826: expected 44 fields, saw 45\nSkipping line 2882: expected 44 fields, saw 45\nSkipping line 2909: expected 44 fields, saw 45\nSkipping line 3005: expected 44 fields, saw 45\nSkipping line 3019: expected 44 fields, saw 45\nSkipping line 3052: expected 44 fields, saw 45\nSkipping line 3062: expected 44 fields, saw 45\nSkipping line 3086: expected 44 fields, saw 45\nSkipping line 3089: expected 44 fields, saw 45\nSkipping line 3134: expected 44 fields, saw 46\nSkipping line 3157: expected 44 fields, saw 45\nSkipping line 3163: expected 44 fields, saw 45\nSkipping line 3177: expected 44 fields, saw 45\nSkipping line 3190: expected 44 fields, saw 45\nSkipping line 3205: expected 44 fields, saw 45\nSkipping line 3209: expected 44 fields, saw 45\nSkipping line 3238: expected 44 fields, saw 45\nSkipping line 3242: expected 44 fields, saw 45\nSkipping line 3255: expected 44 fields, saw 45\nSkipping line 3303: expected 44 fields, saw 45\nSkipping line 3314: expected 44 fields, saw 45\nSkipping line 3322: expected 44 fields, saw 45\nSkipping line 3358: expected 44 fields, saw 45\nSkipping line 3360: expected 44 fields, saw 46\nSkipping line 3377: expected 44 fields, saw 45\nSkipping line 3413: expected 44 fields, saw 45\nSkipping line 3481: expected 44 fields, saw 45\nSkipping line 3496: expected 44 fields, saw 45\nSkipping line 3719: expected 44 fields, saw 45\nSkipping line 3792: expected 44 fields, saw 45\nSkipping line 3807: expected 44 fields, saw 46\nSkipping line 3858: expected 44 fields, saw 45\nSkipping line 3864: expected 44 fields, saw 45\nSkipping line 3902: expected 44 fields, saw 45\nSkipping line 3943: expected 44 fields, saw 45\nSkipping line 3969: expected 44 fields, saw 45\nSkipping line 4024: expected 44 fields, saw 47\nSkipping line 4044: expected 44 fields, saw 45\nSkipping line 4045: expected 44 fields, saw 45\nSkipping line 4112: expected 44 fields, saw 45\nSkipping line 4149: expected 44 fields, saw 45\nSkipping line 4280: expected 44 fields, saw 45\nSkipping line 4282: expected 44 fields, saw 45\nSkipping line 4308: expected 44 fields, saw 45\nSkipping line 4377: expected 44 fields, saw 45\nSkipping line 4390: expected 44 fields, saw 45\nSkipping line 4404: expected 44 fields, saw 45\nSkipping line 4416: expected 44 fields, saw 45\nSkipping line 4423: expected 44 fields, saw 46\nSkipping line 4540: expected 44 fields, saw 45\nSkipping line 4554: expected 44 fields, saw 45\nSkipping line 4556: expected 44 fields, saw 46\nSkipping line 4572: expected 44 fields, saw 45\nSkipping line 4593: expected 44 fields, saw 45\nSkipping line 4614: expected 44 fields, saw 45\nSkipping line 4688: expected 44 fields, saw 45\nSkipping line 4750: expected 44 fields, saw 45\nSkipping line 4764: expected 44 fields, saw 45\nSkipping line 4765: expected 44 fields, saw 45\nSkipping line 4849: expected 44 fields, saw 45\nSkipping line 4865: expected 44 fields, saw 45\nSkipping line 4892: expected 44 fields, saw 45\nSkipping line 4893: expected 44 fields, saw 45\nSkipping line 4897: expected 44 fields, saw 45\nSkipping line 4923: expected 44 fields, saw 45\nSkipping line 4956: expected 44 fields, saw 45\nSkipping line 4957: expected 44 fields, saw 45\nSkipping line 4962: expected 44 fields, saw 45\nSkipping line 4967: expected 44 fields, saw 45\nSkipping line 4971: expected 44 fields, saw 45\nSkipping line 5057: expected 44 fields, saw 45\nSkipping line 5061: expected 44 fields, saw 45\nSkipping line 5097: expected 44 fields, saw 45\nSkipping line 5125: expected 44 fields, saw 45\nSkipping line 5180: expected 44 fields, saw 45\nSkipping line 5207: expected 44 fields, saw 45\nSkipping line 5339: expected 44 fields, saw 45\nSkipping line 5426: expected 44 fields, saw 45\nSkipping line 5474: expected 44 fields, saw 45\nSkipping line 5511: expected 44 fields, saw 45\nSkipping line 5561: expected 44 fields, saw 45\nSkipping line 5563: expected 44 fields, saw 45\nSkipping line 5689: expected 44 fields, saw 45\nSkipping line 5725: expected 44 fields, saw 45\nSkipping line 5759: expected 44 fields, saw 45\nSkipping line 5796: expected 44 fields, saw 45\nSkipping line 5829: expected 44 fields, saw 45\nSkipping line 5854: expected 44 fields, saw 45\nSkipping line 5886: expected 44 fields, saw 45\nSkipping line 5899: expected 44 fields, saw 45\nSkipping line 5901: expected 44 fields, saw 45\nSkipping line 5970: expected 44 fields, saw 45\nSkipping line 5996: expected 44 fields, saw 45\nSkipping line 6085: expected 44 fields, saw 45\nSkipping line 6087: expected 44 fields, saw 45\nSkipping line 6095: expected 44 fields, saw 45\nSkipping line 6096: expected 44 fields, saw 45\nSkipping line 6098: expected 44 fields, saw 45\nSkipping line 6115: expected 44 fields, saw 46\nSkipping line 6158: expected 44 fields, saw 46\nSkipping line 6174: expected 44 fields, saw 45\nSkipping line 6187: expected 44 fields, saw 45\nSkipping line 6218: expected 44 fields, saw 45\nSkipping line 6266: expected 44 fields, saw 45\nSkipping line 6275: expected 44 fields, saw 45\nSkipping line 6279: expected 44 fields, saw 45\nSkipping line 6296: expected 44 fields, saw 45\nSkipping line 6471: expected 44 fields, saw 46\nSkipping line 6494: expected 44 fields, saw 45\nSkipping line 6497: expected 44 fields, saw 45\nSkipping line 6614: expected 44 fields, saw 46\nSkipping line 6714: expected 44 fields, saw 45\nSkipping line 6727: expected 44 fields, saw 45\nSkipping line 6752: expected 44 fields, saw 45\nSkipping line 6763: expected 44 fields, saw 45\nSkipping line 6817: expected 44 fields, saw 45\nSkipping line 6853: expected 44 fields, saw 45\nSkipping line 6904: expected 44 fields, saw 45\nSkipping line 6914: expected 44 fields, saw 45\nSkipping line 6948: expected 44 fields, saw 45\nSkipping line 6969: expected 44 fields, saw 45\nSkipping line 6979: expected 44 fields, saw 45\nSkipping line 7010: expected 44 fields, saw 47\nSkipping line 7024: expected 44 fields, saw 45\nSkipping line 7036: expected 44 fields, saw 45\nSkipping line 7069: expected 44 fields, saw 45\nSkipping line 7146: expected 44 fields, saw 45\nSkipping line 7168: expected 44 fields, saw 45\nSkipping line 7170: expected 44 fields, saw 45\nSkipping line 7317: expected 44 fields, saw 45\nSkipping line 7399: expected 44 fields, saw 45\nSkipping line 7402: expected 44 fields, saw 45\nSkipping line 7496: expected 44 fields, saw 45\nSkipping line 7584: expected 44 fields, saw 45\nSkipping line 7666: expected 44 fields, saw 45\nSkipping line 7690: expected 44 fields, saw 45\nSkipping line 7704: expected 44 fields, saw 47\nSkipping line 7738: expected 44 fields, saw 45\nSkipping line 7773: expected 44 fields, saw 45\nSkipping line 7803: expected 44 fields, saw 45\nSkipping line 7839: expected 44 fields, saw 45\nSkipping line 7850: expected 44 fields, saw 45\nSkipping line 7910: expected 44 fields, saw 45\nSkipping line 7942: expected 44 fields, saw 45\nSkipping line 7959: expected 44 fields, saw 45\nSkipping line 8024: expected 44 fields, saw 45\nSkipping line 8026: expected 44 fields, saw 45\nSkipping line 8028: expected 44 fields, saw 45\nSkipping line 8033: expected 44 fields, saw 45\nSkipping line 8052: expected 44 fields, saw 45\nSkipping line 8129: expected 44 fields, saw 45\nSkipping line 8138: expected 44 fields, saw 45\nSkipping line 8160: expected 44 fields, saw 46\nSkipping line 8244: expected 44 fields, saw 45\nSkipping line 8255: expected 44 fields, saw 45\nSkipping line 8390: expected 44 fields, saw 45\nSkipping line 8400: expected 44 fields, saw 45\nSkipping line 8429: expected 44 fields, saw 45\nSkipping line 8446: expected 44 fields, saw 46\nSkipping line 8565: expected 44 fields, saw 46\nSkipping line 8622: expected 44 fields, saw 46\nSkipping line 8658: expected 44 fields, saw 45\nSkipping line 8742: expected 44 fields, saw 45\nSkipping line 8748: expected 44 fields, saw 45\nSkipping line 8802: expected 44 fields, saw 45\nSkipping line 8844: expected 44 fields, saw 45\nSkipping line 8874: expected 44 fields, saw 45\nSkipping line 8882: expected 44 fields, saw 45\nSkipping line 8885: expected 44 fields, saw 48\nSkipping line 8910: expected 44 fields, saw 45\nSkipping line 8923: expected 44 fields, saw 45\nSkipping line 8947: expected 44 fields, saw 45\nSkipping line 8958: expected 44 fields, saw 45\nSkipping line 9039: expected 44 fields, saw 46\nSkipping line 9090: expected 44 fields, saw 45\nSkipping line 9112: expected 44 fields, saw 45\nSkipping line 9137: expected 44 fields, saw 45\nSkipping line 9201: expected 44 fields, saw 45\nSkipping line 9257: expected 44 fields, saw 45\nSkipping line 9272: expected 44 fields, saw 45\nSkipping line 9390: expected 44 fields, saw 45\nSkipping line 9487: expected 44 fields, saw 45\nSkipping line 9518: expected 44 fields, saw 45\nSkipping line 9554: expected 44 fields, saw 45\nSkipping line 9576: expected 44 fields, saw 45\nSkipping line 9671: expected 44 fields, saw 45\nSkipping line 9690: expected 44 fields, saw 45\nSkipping line 9758: expected 44 fields, saw 45\nSkipping line 9759: expected 44 fields, saw 45\nSkipping line 9767: expected 44 fields, saw 45\nSkipping line 9776: expected 44 fields, saw 45\nSkipping line 9805: expected 44 fields, saw 45\nSkipping line 9834: expected 44 fields, saw 45\nSkipping line 9837: expected 44 fields, saw 45\nSkipping line 9854: expected 44 fields, saw 45\nSkipping line 9890: expected 44 fields, saw 45\nSkipping line 9897: expected 44 fields, saw 45\nSkipping line 9957: expected 44 fields, saw 45\nSkipping line 9979: expected 44 fields, saw 45\nSkipping line 9980: expected 44 fields, saw 45\nSkipping line 10001: expected 44 fields, saw 45\nSkipping line 10002: expected 44 fields, saw 45\nSkipping line 10023: expected 44 fields, saw 45\nSkipping line 10032: expected 44 fields, saw 45\nSkipping line 10051: expected 44 fields, saw 45\nSkipping line 10059: expected 44 fields, saw 46\nSkipping line 10086: expected 44 fields, saw 45\nSkipping line 10102: expected 44 fields, saw 45\nSkipping line 10118: expected 44 fields, saw 45\nSkipping line 10184: expected 44 fields, saw 45\nSkipping line 10199: expected 44 fields, saw 45\nSkipping line 10204: expected 44 fields, saw 45\nSkipping line 10218: expected 44 fields, saw 45\nSkipping line 10224: expected 44 fields, saw 45\nSkipping line 10294: expected 44 fields, saw 45\nSkipping line 10296: expected 44 fields, saw 45\nSkipping line 10331: expected 44 fields, saw 45\nSkipping line 10342: expected 44 fields, saw 45\nSkipping line 10351: expected 44 fields, saw 45\nSkipping line 10414: expected 44 fields, saw 45\nSkipping line 10430: expected 44 fields, saw 45\nSkipping line 10463: expected 44 fields, saw 45\nSkipping line 10478: expected 44 fields, saw 46\nSkipping line 10533: expected 44 fields, saw 45\nSkipping line 10536: expected 44 fields, saw 45\nSkipping line 10539: expected 44 fields, saw 45\nSkipping line 10549: expected 44 fields, saw 45\nSkipping line 10582: expected 44 fields, saw 45\nSkipping line 10588: expected 44 fields, saw 45\nSkipping line 10598: expected 44 fields, saw 45\nSkipping line 10660: expected 44 fields, saw 45\nSkipping line 10733: expected 44 fields, saw 45\nSkipping line 10806: expected 44 fields, saw 45\nSkipping line 10862: expected 44 fields, saw 45\nSkipping line 10905: expected 44 fields, saw 45\nSkipping line 10993: expected 44 fields, saw 45\nSkipping line 11070: expected 44 fields, saw 45\nSkipping line 11084: expected 44 fields, saw 45\nSkipping line 11110: expected 44 fields, saw 45\nSkipping line 11123: expected 44 fields, saw 45\nSkipping line 11128: expected 44 fields, saw 45\nSkipping line 11129: expected 44 fields, saw 45\nSkipping line 11196: expected 44 fields, saw 45\nSkipping line 11210: expected 44 fields, saw 45\nSkipping line 11254: expected 44 fields, saw 45\nSkipping line 11290: expected 44 fields, saw 45\nSkipping line 11365: expected 44 fields, saw 45\nSkipping line 11433: expected 44 fields, saw 45\nSkipping line 11434: expected 44 fields, saw 45\nSkipping line 11469: expected 44 fields, saw 45\nSkipping line 11475: expected 44 fields, saw 45\nSkipping line 11480: expected 44 fields, saw 45\nSkipping line 11513: expected 44 fields, saw 45\nSkipping line 11522: expected 44 fields, saw 45\nSkipping line 11553: expected 44 fields, saw 45\nSkipping line 11610: expected 44 fields, saw 45\nSkipping line 11641: expected 44 fields, saw 45\nSkipping line 11655: expected 44 fields, saw 46\nSkipping line 11689: expected 44 fields, saw 45\nSkipping line 11753: expected 44 fields, saw 45\nSkipping line 11776: expected 44 fields, saw 45\nSkipping line 11797: expected 44 fields, saw 45\nSkipping line 11809: expected 44 fields, saw 45\nSkipping line 11882: expected 44 fields, saw 45\nSkipping line 11915: expected 44 fields, saw 45\nSkipping line 11917: expected 44 fields, saw 46\nSkipping line 11929: expected 44 fields, saw 45\nSkipping line 11956: expected 44 fields, saw 45\nSkipping line 12031: expected 44 fields, saw 45\nSkipping line 12047: expected 44 fields, saw 46\nSkipping line 12160: expected 44 fields, saw 45\nSkipping line 12180: expected 44 fields, saw 45\nSkipping line 12184: expected 44 fields, saw 45\nSkipping line 12224: expected 44 fields, saw 45\nSkipping line 12227: expected 44 fields, saw 45\nSkipping line 12233: expected 44 fields, saw 45\nSkipping line 12251: expected 44 fields, saw 45\nSkipping line 12256: expected 44 fields, saw 45\nSkipping line 12257: expected 44 fields, saw 45\nSkipping line 12259: expected 44 fields, saw 45\nSkipping line 12355: expected 44 fields, saw 45\nSkipping line 12378: expected 44 fields, saw 45\nSkipping line 12398: expected 44 fields, saw 45\nSkipping line 12486: expected 44 fields, saw 45\nSkipping line 12516: expected 44 fields, saw 45\nSkipping line 12588: expected 44 fields, saw 45\nSkipping line 12595: expected 44 fields, saw 45\nSkipping line 12614: expected 44 fields, saw 45\nSkipping line 12642: expected 44 fields, saw 45\nSkipping line 12701: expected 44 fields, saw 45\nSkipping line 12741: expected 44 fields, saw 46\nSkipping line 12771: expected 44 fields, saw 45\nSkipping line 12777: expected 44 fields, saw 45\nSkipping line 12802: expected 44 fields, saw 45\nSkipping line 12892: expected 44 fields, saw 45\nSkipping line 12910: expected 44 fields, saw 47\nSkipping line 12982: expected 44 fields, saw 46\nSkipping line 13024: expected 44 fields, saw 45\nSkipping line 13052: expected 44 fields, saw 45\nSkipping line 13056: expected 44 fields, saw 45\nSkipping line 13158: expected 44 fields, saw 45\nSkipping line 13170: expected 44 fields, saw 45\nSkipping line 13171: expected 44 fields, saw 45\nSkipping line 13186: expected 44 fields, saw 45\nSkipping line 13240: expected 44 fields, saw 45\nSkipping line 13262: expected 44 fields, saw 45\nSkipping line 13374: expected 44 fields, saw 45\nSkipping line 13407: expected 44 fields, saw 45\nSkipping line 13477: expected 44 fields, saw 45\nSkipping line 13540: expected 44 fields, saw 46\nSkipping line 13569: expected 44 fields, saw 45\nSkipping line 13617: expected 44 fields, saw 46\nSkipping line 13651: expected 44 fields, saw 45\nSkipping line 13663: expected 44 fields, saw 45\nSkipping line 13754: expected 44 fields, saw 46\nSkipping line 13775: expected 44 fields, saw 45\nSkipping line 13804: expected 44 fields, saw 45\nSkipping line 13828: expected 44 fields, saw 45\nSkipping line 13865: expected 44 fields, saw 46\nSkipping line 13883: expected 44 fields, saw 45\nSkipping line 13929: expected 44 fields, saw 45\nSkipping line 13948: expected 44 fields, saw 45\nSkipping line 14022: expected 44 fields, saw 45\nSkipping line 14127: expected 44 fields, saw 45\nSkipping line 14148: expected 44 fields, saw 45\nSkipping line 14173: expected 44 fields, saw 45\nSkipping line 14243: expected 44 fields, saw 45\nSkipping line 14254: expected 44 fields, saw 45\nSkipping line 14318: expecte

                   fn        tid  ... War Western
0  titles01/tt0012349  tt0012349  ...   0       0
1  titles01/tt0015864  tt0015864  ...   0       0
2  titles01/tt0017136  tt0017136  ...   0       0
3  titles01/tt0017925  tt0017925  ...   0       0
4  titles01/tt0021749  tt0021749  ...   0       0

[5 rows x 44 columns]

In [12]:
ratings1.describe()

         imdbRating   ratingCount  ...           War       Western
count  13153.000000  1.315300e+04  ...  14332.000000  14332.000000
mean       6.864198  2.659931e+04  ...      0.031887      0.021909
std        1.121516  6.558283e+04  ...      0.175705      0.146392
min        1.000000  5.000000e+00  ...      0.000000      0.000000
25%        6.300000  6.020000e+02  ...      0.000000      0.000000
50%        7.000000  3.990000e+03  ...      0.000000      0.000000
75%        7.600000  2.090500e+04  ...      0.000000      0.000000
max        9.900000  1.183395e+06  ...      1.000000      1.000000

[8 rows x 38 columns]

In [13]:
C= ratings1['imdbRating'].mean()
C

6.864198281760789

In [15]:
m= ratings1['ratingCount'].quantile(0.9)
m

71277.20000000001

In [16]:
movies = ratings1.copy().loc[ratings1['ratingCount'] >= m]
movies.shape

(1316, 44)

In [18]:
def rating_score(x, m=m, C=C):
    v = x['ratingCount']
    R = x['imdbRating']
    # Calculation by using IMDB formula
    return (v/(v+m) * R) + (m/(m+v) * C)

In [19]:
movies['score'] = movies.apply(rating_score, axis=1)

In [20]:
movies = movies.sort_values('score', ascending=False)

In [21]:
movies[['title', 'ratingCount', 'imdbRating', 'score']].head(10)

                                                  title  ...     score
7104                 Breaking Bad (TV Series 2008–2013)  ...  9.266164
4874  Game of Thrones - Das Lied von Eis und Feuer (...  ...  9.196398
138                             Die Verurteilten (1994)  ...  9.161624
77                                      Der Pate (1972)  ...  9.013496
207                              The Dark Knight (2008)  ...  8.875197
137                                 Pulp Fiction (1994)  ...  8.845026
80                                    Der Pate 2 (1974)  ...  8.839872
7985                        Sherlock (TV Series 2010– )  ...  8.809400
165                                   Fight Club (1999)  ...  8.750662
162           Der Herr der Ringe - Die Gefährten (2001)  ...  8.746138

[10 rows x 4 columns]

In [27]:
trending=[i for i in range(1,(movies.shape[0]+1))]
movies["Trending"]=trending
movies[['Trending','title', 'ratingCount', 'imdbRating', 'score']].head(10)

      Trending  ...     score
7104         1  ...  9.266164
4874         2  ...  9.196398
138          3  ...  9.161624
77           4  ...  9.013496
207          5  ...  8.875197
137          6  ...  8.845026
80           7  ...  8.839872
7985         8  ...  8.809400
165          9  ...  8.750662
162         10  ...  8.746138

[10 rows x 5 columns]

In [ ]:
In this way we create a new column called Trending which recommends the movies according to trends.